### ISSUE TITLE
함수 생성

### ISSUE THREAD

**Issue by wongakim-99** [wongakim-99/test-repository#2]
승우야 파이썬 함수 아무거나 만들어봐 복붙하든 gpt 쓰든 상관 없음

**Comment by wongakim-99** [comment]
너무 밋밋한 함수다....좀 더 멋있는 함수를 만들어!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
정렬 알고리즘에서 QuickSort 알고리즘을 파이썬으로 구현한거 그거 커밋ㄱㄱ

**Comment by SSeungWOOO** [comment]
아주멋진 퀵소트 파이썬함수

**Comment by wongakim-99** [comment]
흐음....좋았어
