### ISSUE TITLE
for 승우

### ISSUE THREAD

**Issue by wongakim-99** [wongakim-99/test-repository#3]
## **너를 위해 과제를 준비했디.**
**_정렬 알고리즘 아무거나 하나 소스코드를 커밋해라._** 

**조건1.**
sort_algorithm.py 파일을 하나 생성할것(언어는 파이썬 사용)😯

**조건2.**
어떤 정렬 알고리즘인지 주석 또는 파일을 하나 더 생성해서 적을것 💁‍♂️

**조건3.**
지금 생성한 이 이슈번호 맞춰서 커밋 제목 작성하기

**Comment by wongakim-99** [comment]
# ChatGPT or 구글링 대환영 💓

**Comment by SSeungWOOO** [comment]
과제에 답변이 되었나요

**Comment by wongakim-99** [comment]
# 오오오오오🫵  🤜🤛  🫰

쉐끼 잘 하면서
