### ISSUE TITLE
자료구조 & 알고리즘 테스트 for 승우

### ISSUE THREAD

**Issue by wongakim-99** [wongakim-99/test-repository#5]
# 자료구조 스택(Stack)에 대해서 한번 설명해볼것

**_조건 : 아래와 같은 내용을 하나 설명한다._**

**1. 스택의 개념**
**2. 스택에 작동원리 (아이패드 있지? 아이패드에 그림 그린다음 그거 캡쳐해서 Add a comment에 올리면 올라감)**
**3. 스택 제공 연산 종류** 
**4. 스택이 어디에 활용되는가?**
**5. 파이썬을 활용해서 스택 구현 소스코드 커밋**

**_1~4 번은 Add a comment에 설명하고 5번은 파이썬 소스코드 커밋_**

**Comment by wongakim-99** [comment]
**※참고사항※**

# 위의 내용들은 전부 구글링하면 다 나옵니다.

**Comment by wongakim-99** [comment]
# 이슈 번호에 맞춰서 커밋하는거 잊지말긔

**Comment by SSeungWOOO** [comment]
![IMG_0100](https://github.com/user-attachments/assets/850173a5-0f8c-428d-87eb-2ed4eeef8ba5)

**Comment by SSeungWOOO** [comment]
#2024-08-10과제

#스택이란??

#스택은 한쪽 끝에서만 데이터를 넣고 뺼수있는 후입선출 형태의 선형 자료구조이다.
#제공연산 종류: 
#pop():스택에서 가장위에 있는 항목을 제거
#push(item):item 하나를 스택의 가장 윗부분에 추가
#peek():스택의 가장위에 있는항목을 반환한다
#isEmpty():스택이 비어있떄 true를 반환한다

#스택의 활용 예시:

#웹 브라우저 방문기록(뒤로가기)
#실행 취소(undo) (되돌리기기능)
#역순 문자열 만들기
#후위 표기법 계산

**Comment by wongakim-99** [comment]
잘 했는데 몇 가지 개선해야할점

**1. 파일명은 영어로 -> 새로 생성한 파일 보면 #2024-08-10과제.py 로 되어있는데 이거는 파일명은 영어로 하길**
**2. 코멘트 마크다운 문법 쓰면 좀 더 깔끔해짐**

![Image](https://github.com/user-attachments/assets/681f51fb-4d99-427e-b791-c3f7c01010cd)
▲ 마크다운 사용예시

[https://gist.github.com/ihoneymon/652be052a0727ad59601](url)


**그림 조금만 더 공들여서..^^**
